baseurl = "/"
title = "Simon Sayz"
languageCode = "en-us"
theme = "github-style"
googleAnalytics = "UA-143283233-1"
disqusShortname = "disqus_ZaSIgvoejX"



[params]
    author = "Simon Sayz"
    status = "<enjoy> My Blog </enjoy>"
    description = "I am an Aspiring Data Scientist: Comfortable in R, Python, Tableau, Shiny, SQL"
    twitter = "simonsayzdgtl"
	linkedin = "simon-sayz"
	github = "tagasimon"
	shiny = "http://67.207.81.13/shiny/"
	tabl = "https://public.tableau.com/profile/kazooba.simon"
    email = "smkabz@gmail.com"
    avatar = ""
    url = "https://simonsayz.xyz/"
    keywords = "blog, R, tidyverse, Data Science"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
