baseurl = "/"
languageCode = "en-us"
title = "Home"
theme = "hyde-hyde"
googleAnalytics = "UA-143283233-1"
disqusShortname = "disqus_ZaSIgvoejX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
[[menu.main]]
    name = "About Me"
    url = "/about/"
[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"

[params]
    description = "Kinda a Data Scientist"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
[params.social]
	twitter = "https://twitter.com/simonsayzdgtl"
	linkedin = "https://www.linkedin.com/in/simon-sayz/"
	github = "https://github.com/tagasimon"
    gravatar = "smkabz@gmail.com"

